config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'pages/home', to: 'pages#home'

  # get '/recipes', to: 'recipes#index'
  # get '/recipes/new', to: 'recipes#new', as: 'new_recipe'
  # post '/recipes', to: 'recipes#create'
  # get '/recipes/:id', to: 'recipes#show', as: 'recipe'
  resources :recipes do
    resources :comments, only: [:create]
  end
  get '/signup', to: 'chefs#new'
  resources :chefs, except: [:new]
  resources :ingredients, except: [:destroy]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  mount ActionCable.server => '/cable'

  get '/chat', to: 'chatrooms#show'

  resources :messages, only: [:create]
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates_presence_of :name, :description, :chef_id
  validates :name, length: {maximum: 200}
  validates :description, length: {minimum: 5, maximum: 500}
  belongs_to :chef
  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients
  default_scope -> {order(updated_at: :desc)}
  has_many :comments, dependent: :destroy

  def self.search(search)
    if search
      where(["name LIKE ?", "%#{search}%"])
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    # @recipes = Recipe.paginate(page: params[:page], per_page: 3)
      @recipes = Recipe.paginate(page: params[:page], per_page: 3)
  end

  def show
    @comment = Comment.new
    @comments = @recipe.comments.paginate(page: params[:page], per_page: 3)
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.chef = current_chef
    if @recipe.save
      flash[:success] = "Recipe was successfully created"
      redirect_to recipe_path(@recipe)
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    if @recipe.update(recipe_params)
      flash[:success] = "Recipe was successfully updated"
      redirect_to recipe_path(@recipe)
    else
      render 'edit'
    end
  end

  def destroy
    @recipe.destroy
    flash[:danger] = "Recipe was successfully deleted"
    redirect_to recipes_path
  end

  private
  def recipe_params
    params.require(:recipe).permit(:name, :description, ingredient_ids: [])
  end

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def require_same_user
    if current_chef != @recipe.chef && !current_chef.admin?
      flash[:danger] = "You can only edit or delete your own recipes"
      redirect_to recipes_path
    end
  end
end

app/views/recipes/_form.html.erb
<%= render "shared/errors", obj: @recipe %>
<div class="row">
  <div class="col-md-12">
    <%= form_for(@recipe, :html => {class: "form-horizontal", role: "form"})  do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, rows: 10, class: "form-control" %>
    </div>
    <div class="form-group">
      <div class="row">
        <div class="col-md-12">
          <%= f.collection_check_boxes :ingredient_ids, Ingredient.all, :id, :name do |cb| %>
          <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="form-group">
      <%= f.submit "Save", class: "btn btn-lg btn-primary btn-xlarge" %>
    </div>
    <% end %>
  </div>
  <div class="col-md-4 col-md-offset-4 color-match">
    [ <%= link_to "Cancel request and return to recipe listing", recipes_path %> ]
  </div>
</div>

app/views/recipes/_recipe.html.erb
<% obj.each do |recipe| %>
<div class="row">
  <div class="col-md-2">
    <section class="chef-info center">
      <!-- <%= image_tag "gravatar.jpg", width: 100, height: 100, id: "show-img"%> -->
      <%= image_tag recipe.chef.image.url(:thumb), id: "show-img"%>
    </section>
  </div>
  <div class="col-md-8 well">
  <h4><%= link_to recipe.name, recipe_path(recipe), class: "recipe-title"%></h4>
  <p><%= truncate(recipe.description, length: 150, omission: "...") %></p>
  <% if recipe.ingredients.any? %>
  <p><strong>Ingredients:</strong>
  <% recipe.ingredients.each do |ing| %>
  <span class="badge"><%= link_to ing.name, ingredient_path(ing)%></span>
  <% end %>
</p>
  <% end %>
  <p><small>created <%= time_ago_in_words(recipe.created_at) %> ago by <%= recipe.chef.chefname.capitalize %>
                        | <%= pluralize(recipe.comments.count, "Comment") %></small></p>
  <% if logged_in? && (current_chef == recipe.chef || current_chef.admin?) %>
  <%= link_to "Edit", edit_recipe_path(recipe), class: "btn btn-primary" %>
  <%= link_to "Delete", recipe_path(recipe), method: :delete, data: { confirm: 'Are you sure to delete?'}, class: "btn btn-danger" %>
  <% end %>
  </div>
</div>
<% end %>

app/views/recipes/edit.html.erb
<%=  render 'shared/page_title', title: "Edit recipe"%>
<%= render 'form' %>

app/views/recipes/index.html.erb
<%= render 'shared/page_title', title: "showing all Recipes" %>
<div align="center">
  <%= will_paginate @recipes %>
</div>
<%= render 'recipe', obj: @recipes %>
<div align="center">
  <%= will_paginate @recipes %>
</div>

app/views/recipes/new.html.erb
<%=  render 'shared/page_title', title: "create a new recipe"%>
<%= render 'form' %>

app/views/recipes/show.html.erb
<%= render 'shared/page_title', title: @recipe.name %>
<div class="well col-md-8 col-md-offset-2">
  <h4 class="center description"><strong>Description: </strong></h4>
  <hr>
  <%= simple_format(@recipe.description) %>
  <hr>
  <% if @recipe.ingredients.any? %>
  <p><strong>Ingredients:</strong>
  <% @recipe.ingredients.each do |ing| %>
  <span class="badge"><%= link_to ing.name, ingredient_path(ing)%></span>
  <% end %>
</p>
  <% end %>
  <% if logged_in? && (current_chef == @recipe.chef || current_chef.admin?)%>
  <div class="pull-left show-actions">
    <%= link_to "Edit", edit_recipe_path(@recipe), class: "btn btn-primary" %>
    <%= link_to "Delete", recipe_path(@recipe), method: :delete, data: { confirm: 'Are you sure to delete?'}, class: "btn btn-danger" %>
    <% end %>
    <%= link_to "Back", recipes_path, class: "btn btn-primary" %>
  </div>
  <div class="pull-right">
    <p class="center">
      <em>Created By:</em>
    </p>
    <p class="center">
       <!-- <%= link_to image_tag("gravatar.jpg", width: 100, height: 100, id: "show-img"), chef_path(@recipe.chef)%> -->
       <%= link_to image_tag(@recipe.chef.image.url(:thumb), id: "show-img"), chef_path(@recipe.chef) %>
    </p>
    <p class="center">
      <small><%= @recipe.chef.chefname %></small>
      <div class="pull-right">Created <%= time_ago_in_words(@recipe.created_at)%> ago</div>
    </p>
  </div>
</div>

<% if logged_in? %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h3>Comments: </h3>
      <hr>
      <%= form_for([@recipe, @comment], remote: true, :html => {class: "form-horizontal", role: "form"})  do |f| %>
      <div class="form-group">
        <%= f.label :description, "Comment" %>
        <%= f.text_area :description, rows: 8, class: "form-control", placeholder: "Enter comment here" %>
      </div>
      <div class="form-group">
        <%= f.submit "Submit Comment", class: "btn btn-lg btn-primary btn-xlarge" %>
      </div>
    <% end %>
    <hr>
  </div>
</div>
<% end %>

<% if @recipe.comments.count != 0 %>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h3>Prior Comments:</h3>
    <div id="messages">
        <%= render partial: 'comments/comments', object: @comments %>
    </div>
  </div>
</div>
<% else %>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h3>No comments yet</h3>
  </div>

</div>
<% end %>