config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'pages/home', to: 'pages#home'

  # get '/recipes', to: 'recipes#index'
  # get '/recipes/new', to: 'recipes#new', as: 'new_recipe'
  # post '/recipes', to: 'recipes#create'
  # get '/recipes/:id', to: 'recipes#show', as: 'recipe'
  resources :recipes do
    resources :comments, only: [:create]
  end
  get '/signup', to: 'chefs#new'
  resources :chefs, except: [:new]
  resources :ingredients, except: [:destroy]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  mount ActionCable.server => '/cable'

  get '/chat', to: 'chatrooms#show'

  resources :messages, only: [:create]
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, presence: true, length: {minimum: 3, maximum: 25}
  validates_uniqueness_of :name
  has_many :recipe_ingredients
  has_many :recipes, through: :recipe_ingredients
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

  before_action :set_ingredient, only: [:edit, :update, :show]
  before_action :require_admin, except: [:show, :index]

  def index
    @ingredients = Ingredient.paginate(page: params[:page], per_page: 3)
  end

  def new
    @ingredient = Ingredient.new
  end

  def create
    @ingredient = Ingredient.new(ingredient_params)
    if @ingredient.save
      flash[:success] = "Ingredient successfully saved"
      redirect_to ingredient_path(@ingredient)
    else
      render 'new'
    end
  end

  def update
    if @ingredient.update(ingredient_params)
      flash[:success] = "Ingredient successfully updated"
      redirect_to ingredient_path(@ingredient)
    else
      render 'edit'
    end
  end

  def edit
    @ingredient = Ingredient.find(params[:id])
  end

  def show
    @ingredient_recipes = @ingredient.recipes.paginate(page: params[:page], per_page: 5)
  end

  private
def set_ingredient
  @ingredient = Ingredient.find(params[:id])
end

def ingredient_params
  params.require(:ingredient).permit(:name)
end

def require_admin
  if !logged_in? || (logged_in? && !current_chef.admin?)
    flash[:danger] = "Only admin can perform that task"
    redirect_to ingredients_path
  end

  end
end

app/views/ingredients/_form.html.erb
<div class="row">
  <div class="col-md-12">
    <%= form_for(@ingredient, :html => {class: 'form-horizontal', role: 'form'}) do |f| %>
      <%= render "shared/errors", obj: @ingredient%>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
        <div class="form-group">
          <%= f.submit(@ingredient.new_record? ? "Add Ingredient" : "Update Ingredient", class: "btn btn-primary") %>
        </div>
    <% end %>
  </div>
  <div class="col-md-4 col-md-offset-4 color-match">
    [ <%= link_to "Cancel request and return to ingredient listing", ingredients_path %> ]
  </div>
</div>

app/views/ingredients/edit.html.erb
<%= render 'shared/page_title', title: 'Edit ingredient name' %>
<%= render 'form' %>

app/views/ingredients/index.html.erb
<%=  render 'shared/page_title', title: 'Available Ingredients'%>
<div align="center">
  <%= will_paginate @ingredients %>
  <% @ingredients.each do |ing| %>
  <div class="row">
    <div class="col-md-4 col-md-offset-4 well center">
    <h4><%= link_to ing.name.capitalize, ingredient_path(ing), class:"chef-title"%></h4>
    <p><small><%= pluralize(ing.recipes.count, "recipe") if ing.recipes %></small></p>
    <% if logged_in? && current_chef.admin?%>
    <p><%= link_to "Edit the ingredients", edit_ingredient_path(ing),class: "chef-title"%></p>
    <% end %>
    </div>
  </div>
  <% end %>
</div>
<div align="center">
  <%= will_paginate @ingredients %>
</div>

app/views/ingredients/new.html.erb
<%= render 'shared/page_title', title: 'Create a new ingredient' %>
<%= render 'form' %>

app/views/ingredients/show.html.erb
<%= render 'shared/page_title', title: "#{@ingredient.name}" %>

<% if @ingredient_recipes.count != 0 %>
<h4 align="center">Recipes containing <%= @ingredient.name %></h4>
<div align="center">
<%= will_paginate @ingredient_recipes %>
</div>
<%= render 'recipes/recipe', obj: @ingredient_recipes %>
<% else %>
<h4 align="center">No recipe yet</h4>
<% end %>